package com.example.chet.config.tests.tests;// Generated by Selenium IDE
import com.example.chet.config.tests.AuthBase;
import com.example.chet.config.tests.TestBasClass;
import org.junit.Assert;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.Test;
import org.testng.annotations.DataProvider;


public class ChangeTest extends AuthBase {



  @Test()
  public void change() {
//    appMan.getNavHelp().OpenMainPage();
//    appMan.getAuthHelp().EnterLoginAndPassword();
    appMan.getChangeHelp().ChangeDescr();
    Assert.assertEquals("fghdfghdfg",appMan.getChangeHelp().getChangeDescr());
    appMan.getNavHelp().OpenMainPage();


  }

}
