package com.example.chet.config.tests.tests;// Generated by Selenium IDE

import com.example.chet.config.tests.AuthBase;
import com.example.chet.config.tests.TestBasClass;
import org.junit.Assert;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class CreateTest extends AuthBase {

    @Test
    public void create() {
//        appMan.getNavHelp().OpenMainPage();
//        appMan.getAuthHelp().EnterLoginAndPassword();
        appMan.getChangeHelp().SetNewRepNameAndCreate();
        Assert.assertEquals("dfgd", appMan.getChangeHelp().getNewRep());
        appMan.getNavHelp().OpenMainPage();

    }


}
