package com.example.chet.config.t3.tests;// Generated by Selenium IDE
import com.example.chet.config.t3.TestBasClass;
import com.example.chet.config.t3.User;
import org.apache.commons.lang3.RandomStringUtils;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.nio.charset.Charset;
import java.util.Random;
import java.util.concurrent.TimeUnit;

public class LoginTest extends TestBasClass {

  @Test
  public void   untitled() {
//    appMan.getNavHelp().OpenMainPage();
    appMan.getAuthHelp().EnterLoginAndPassword();
    User user=appMan.getAuthHelp().getCreatedUser();
    Assert.assertEquals("olejiksin",user.getLogin());
    Assert.assertEquals("QaZWsXEdC99", user.getPassword());
    appMan.getAuthHelp().SubmitData();


  }


}
