package com.example.chet.config.t3;// Generated by Selenium IDE

import org.junit.BeforeClass;


public class TestBasClass {
    protected static AppMan appMan;

    @BeforeClass
    public static void setUp() {
//        System.setProperty("webdriver.gecko.driver", "C:\\Users\\oleji\\Downloads\\geckodriver.exe");
//        driver = new FirefoxDriver();
//        js = (JavascriptExecutor) driver;
//        vars = new HashMap<String, Object>();
        appMan = AppMan.getInstance();
    }


}
