package com.example.chet.config.tests;// Generated by Selenium IDE

import org.junit.BeforeClass;

import java.io.IOException;


public class TestBasClass {
    protected static AppMan appMan;

    @BeforeClass
    public static void setUp() throws IOException {
        appMan = AppMan.getInstance();
    }


}
