package com.example.chet.config.t3;// Generated by Selenium IDE


import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


public class TestData {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private ObjectMapper mapper;
  private XmlMapper xmlMapper;
  @BeforeClass
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\Users\\oleji\\Downloads\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    mapper = new ObjectMapper();
    xmlMapper=new XmlMapper();
  }
//  @DataProvider
//  private Object[] parseData(){
//    return new Object[]{
//
//    };
//  }

  @Test()
  public void change() throws IOException {
    List<User> list=new ArrayList<>();
    int n=15;
    for(int i=0;i<3;i++){
      list.add(new User(getAlphaNumericString(n),getAlphaNumericString(n)));
    }
    xmlMapper.writeValue(new File("filename.txt"),list);

    User user = new User(getAlphaNumericString(n), "QaZWsXEdC99");

    driver.get("https://hub.docker.com/");
    driver.findElement(By.id("log_in")).click();
    driver.findElement(By.id("nw_username")).sendKeys(user.getLogin());
    driver.findElement(By.id("nw_password")).click();
    driver.findElement(By.id("nw_password")).sendKeys(user.getPassword());
    driver.findElement(By.id("nw_submit")).click();

  }

  private String getAlphaNumericString(int n) {

    String AlphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            + "0123456789"
            + "abcdefghijklmnopqrstuvxyz"
            +"~!@#$%^&*()_+<,>.?/]}{[";

    StringBuilder sb = new StringBuilder(n);

    for (int i = 0; i < n; i++) {
      int index
              = (int)(AlphaNumericString.length()
              * Math.random());
      sb.append(AlphaNumericString
              .charAt(index));
    }
    return sb.toString();
  }
}
