package com.example.chet.config;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;


import java.util.*;
public class RegtestTest {
  WebDriver driver ;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\Users\\oleji\\Downloads\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void regtest() {
    driver.get("https://pikabu.ru/");
    driver.manage().window().setSize(new Dimension(1216, 729));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("TriPek");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("7klass");
    driver.findElement(By.cssSelector(".auth__field:nth-child(7) > .button_success")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".auth__field:nth-child(7) > .button_success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".player__overlay"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}